//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geez.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.ServiceProvider = new HashSet<ServiceProvider>();
        }
    
        public long Id { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string Zone { get; set; }
        public string Street { get; set; }
        public string Details { get; set; }
    
        public virtual ICollection<ServiceProvider> ServiceProvider { get; set; }
    }
}
