//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geez.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long Id { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public string MSISDN { get; set; }
        public string USSDServiceCode { get; set; }
        public string USSDRequestString { get; set; }
        public Nullable<bool> Response { get; set; }
        public Nullable<bool> ChargingFlag { get; set; }
        public Nullable<decimal> ChargeCode { get; set; }
    }
}
