//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geez.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public ServiceProvider()
        {
            this.Checkin = new HashSet<Checkin>();
            this.ServiceProviderPicture = new HashSet<ServiceProviderPicture>();
            this.ServiceProviderRating = new HashSet<ServiceProviderRating>();
            this.Service = new HashSet<Service>();
            this.Event = new HashSet<Event>();
            this.Recommendation = new HashSet<Recommendation>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public long AddressId { get; set; }
        public string OrganizationName { get; set; }
        public string OpeningDays { get; set; }
        public string Details { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Checkin> Checkin { get; set; }
        public virtual ICollection<ServiceProviderPicture> ServiceProviderPicture { get; set; }
        public virtual ICollection<ServiceProviderRating> ServiceProviderRating { get; set; }
        public virtual ICollection<Service> Service { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Recommendation> Recommendation { get; set; }
    }
}
