//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geez.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.ServiceProviderRating = new HashSet<ServiceProviderRating>();
            this.ServiceProvider = new HashSet<ServiceProvider>();
        }
    
        public int Id { get; set; }
        public string ServiceName { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<ServiceProviderRating> ServiceProviderRating { get; set; }
        public virtual ICollection<ServiceProvider> ServiceProvider { get; set; }
    }
}
