//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geez.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProviderRating
    {
        public long Id { get; set; }
        public int ServiceProviderId { get; set; }
        public int ServiceId { get; set; }
        public decimal AverageRating { get; set; }
        public int RatingCount { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
    }
}
